# Site https://www.askmedave.xyz
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: David Diaz Adames
title: Systems Administrator
email: davidadames608@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://www.askmedave.xyz
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  adamesd1
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: david-diaz-adames
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
# icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
# url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
   A Solutions-Focused IT Professional offering extensive experience in network administration, and troubleshooting supporting clients from a broad spectrum of industries. Skilled in applying comprehensive strategies to develop virtual machines, IT structures, and processes.

 # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
 # - Lists
 #  - Tables
 # - <a href="google.com">Links</a>
 # - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Bryn Mawr College
        sub_title: Systems Administrator
        caption: August 2019 - present
        link: brynmawr.edu
        quote: >
          Bryn Mawr College is a women's liberal arts college in Bryn Mawr, Pennsylvania. Founded as a Quaker institution in 1885, Bryn Mawr is one of the Seven Sister colleges.
        description: | # this will include new lines to allow paragraphs
          Responsibilities include hardware and software support for teaching and research, faculty desktop and laptop support, and administration of curriculum resources. Reporting to the Chair of the Computer Science department. I am responsible for the installation, integration, maintenance, and integrity of all hardware and software running on all computing systems in the department. In addition, I am also responsible for the condition and upkeep of all teaching and research labs. I participate in the day-to-day management of the systems, support of the user community and software support for research and teaching. I am also involved in a number of initiatives, including developing software, course materials, and exploring new and innovative uses of research in the classroom. I co-report to the College’s Chief Information Officer/Director of Libraries and collaborate with relevant teams in the Library Information and Technology Services division. I am also a member of the College's Information Stewardship Council. I support the departmental computational infrastructure of nearly 80 workstations, associated servers, peripherals and electronic services (printing, web site, email, wiki, etc.) Support the infrastructure of 3 Oracle Solaris servers and two 25-workstation teaching/general use laboratories with dual-boot (Windows and Linux) computers. With additional research laboratories and workstations including Macs and ancillary equipment.
      - layout: right
        title: Hahnemann Hospital
        sub_title: Technical Support Analyst
        caption: November 2018 - September 2019
        link: https://www.hahnemannhospital.com/
        quote: >
          Hahnemann University Hospital was a tertiary care center in Center City, Philadelphia, and the Center City Philadelphia teaching hospital of Drexel University College of Medicine.
        description: | # this will include new lines to allow paragraphs
          Handpicked to lead IT delivery solutions for a medium sized hospital. Recognized for consistently delivering high standards in system management ensuring optimal levels of operability and minimal downtime. Experienced in managing the ongoing troubleshooting including providing Tier 1 and 2 level escalation support. Performs setup, scripting, installation, configuration, and deployment of PC/laptop hardware and software to business areas in accordance with local and System guidelines. Supports and administers audio-visual and mobile device equipment, working with vendors and training customers. Managed a wide array of tasks that included installing, configuring, and maintaining VMware environments, designing and deploying template and parent VMs, troubleshoot and resolve VMware infrastructure related issues.
      - layout: right
        title: Merakey
        sub_title: Desktop Technician
        caption: August 2018 - November 2018
        link: https://www.merakey.org/ 
        quote: >
          Nonprofit specializing in Behavioral Health, Education and Autism, and Intellectual and Developmental Disabilities.
        description: | # this will include new lines to allow paragraphs
          Worked with partners during change control activities to ensure smooth migrations and implementations, including performing change tasks. Configured and tested networks infrastructure, application programming, and software applications in alignment with business requirements. Deploys Active Directory and Windows Server Support while delivering minimum downtime and impact to business operations. Possesses advance skills in installing Windows OS, printers, and business applications. Supported users with their computers, printers and phones. (Consists of Windows 7/10 environment using office 2010/2016 with Dell Laptops and Desktops along with HP Printers and Ricoh Copiers.) Handle re-imaging or redeployment of computer equipment. Manage and create user accounts in Active Directory and Exchange. Work with other IT staff to ensure customer service to the internal customers. Keep desktop OS and desktop software up to date. Coordinate printer setup and repairs. Contact vendors and contractors as needed.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: La Salle University
        sub_title: BA Information Technology
        caption: Date Range 2012 - 2016
        quote: >
          La Salle University is a private, Catholic university in Philadelphia, Pennsylvania. The university was founded in 1863 by the Institute of the Brothers of the Christian Schools and named for St. Jean-Baptiste de La Salle. 
        description: | # this will include new lines to allow paragraphs
          The program is designed for those students interested in the study of networks and client support systems, with an option for evening classes for students to accommodate busy schedules.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Apart from being a Systems Administrator, I enjoy my time both being outdoors, and indoors. During the warmer months here in Philadelphia, I enjoy playing basketball, traveling, and swimming. When forced indoors, I follow a number of movies and television shows, I am an aspiring videogame developer, and I spend my free time exploring the latest technology advancements in the front-end web development world.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
